name: ecommerce_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
    - family: MontserratSemibold
      fonts:
        - asset: assets/fonts/MontserratSemibold.ttf
          weight: 600
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
    - family: MontserratExtrabold
      fonts:
        - asset: assets/fonts/MontserratExtrabold.ttf
          weight: 800
    - family: CM Sans Serif
      fonts:
       - asset: assets/fontz/cm_sans_serif_2012.ttf
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imagez/
    - assets/images/
    - assets/images/onboarding/
#flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets//images/splash_logo.png
  android: true
  ios: true
  web: false
