name: ecommerce_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #font_awesome_flutter: ^10.7.0
  flutter_lints: ^5.0.0
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.2.3  #(لتحميل الصور بكفاءة)

dev_dependencies:
  flutter_test:
    sdk: flutter





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/MontserratLight.ttf
          weight: 300
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
    - family: MontserratSemibold
      fonts:
        - asset: assets/fonts/MontserratSemibold.ttf
          weight: 600
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
    - family: MontserratExtrabold
      fonts:
        - asset: assets/fonts/MontserratExtrabold.ttf
          weight: 800
    - family: CM Sans Serif
      fonts:
       - asset: assets/fontz/cm_sans_serif_2012.ttf
    - family: ArimoBold
      fonts:
       - asset: assets/fonts/Arimo-Bold.ttf
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imagez/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/social/
    - assets/images/home/
    - assets/images/maincat/
    - assets/images/cards/ 
    - assets/images/home_prod1/

    

